//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    public partial class Browsing
    {
        public string ID { get; set; }//CUSTOMERID
        public string ItemID { get; set; }
        public string BrowsingTime { get; set; }
    }

    public class BrowsingDBContext : DbContext
    {
        public DbSet<Browsing> Browsings { get; set; }
    }
}
