//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    public partial class Cart
    {
        public string CustomerID { get; set; }
        public string CartID { get; set; }//itemid
        public string ItemCount { get; set; }
        public string CartPrice { get; set; }
    }
    public class CartDBContext : DbContext
    {
        public DbSet<Cart> Carts { get; set; }
    }
}
