//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class CreditCard
    {
        public string CustomerID { get; set; }
        public string CreditCardID { get; set; }
        public string ReceivingInfoCustomerID { get; set; }
   
    }
    public class CreditCardDBContext : DbContext
    {
        public DbSet<CreditCard> CreditCards { get; set; }
    }
}
