//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;


    public partial class Item
    {
        public string ItemID { get; set; }
        public string ShopID { get; set; }
        public string ItemPrice { get; set; }
        public string ItemName { get; set; }
        public string ItemInfo { get; set; }
        public string ItemPic { get; set; }
        public string ItemSales { get; set; }
        public int ItemRemain { get; set; }
    

    }

    public class ItemDBContext : DbContext
    {
        public DbSet<Item> Items { get; set; }
    }
}
