//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Order
    {
        
        public int OrderID { get; set; }
        public string ShopID { get; set; }
        public string CustomerID { get; set; }
        public string OrderPrice { get; set; }
        public string OrderCount { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public string OrderState { get; set; }
    }
    public class OrderDBContext : DbContext
    {
        public DbSet<Order> Orders { get; set; }
    }
}
