//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class OrderDetail
    {
       
        public string OrderDetailID { get; set; } //订单中本商品对应订单、物品、物件表作为tuple时新增主键取代双主键
        public string OrderID { get; set; } //订单编号
        public string ItemID { get; set; }
        public int OrderDetailCount { get; set; }
    
    }
    
}
