//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class OrderItem
    {
       
        public string OrderItemID { get; set; }
        public int OrderID { get; set; }
        public string ItemID { get; set; }
        public string OrderDetailCount { get; set; }
    
    }
    public class OrderItemDBContext : DbContext
    {
        public DbSet<OrderItem> OrderItems { get; set; }
    }
}
