//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class ReceivingInfo
    {
        public string ID { get; set; }//customerid
        public string Address { get; set; }
        public string ReceivingName { get; set; }
        public string ReceivingPhone
        {
            get; set;
        }
        public class ReceivingInfoDBContext : DbContext
        {
            public DbSet<ReceivingInfo> ReceivingInfos { get; set; }
        }
    }
}
