//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    public partial class Saler
    {
    
        public string SalerID { get; set; }
        public string SalerPassword { get; set; }
        public string SalerInfo { get; set; }
        public string SalerPhone { get; set; }
    }
    public class SalerDBContext : DbContext
    {
        public DbSet<Saler> Salers { get; set; }
    }
}
