//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public string ShopID { get; set; }
        public string ShopName { get; set; }
        public string SalerCredit { get; set; }
        public string SalerID { get; set; }
    
        public virtual Saler Saler { get; set; }
    }
}
